@echo off
setlocal DisableDelayedExpansion
chcp 65001 >nul
set "PYTHONUTF8=1"
set "PYTHONDONTWRITEBYTECODE=1"
cd /d "%~dp0"
if defined PYTHON_EXE goto run_absolute
if defined SKILL_SYNC_PYTHON (
  set "PYTHON_EXE=%SKILL_SYNC_PYTHON%"
  goto run_absolute
)
where python >nul 2>nul
if not errorlevel 1 (
  python "%~dp0scripts\runtime_support.py" %*
  goto done
)
where py >nul 2>nul
if not errorlevel 1 (
  py -3 "%~dp0scripts\runtime_support.py" %*
  goto done
)
echo No Python command found. Ask the local agent to run bootstrap.py with its sys.executable.
echo Use the profile shortcut generated by bootstrap, or set PYTHON_EXE to an absolute Python path.
pause
exit /b 1
:run_absolute
"%PYTHON_EXE%" "%~dp0scripts\runtime_support.py" %*
:done
if errorlevel 1 pause
